# Generated by Django 3.2 on 2021-04-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedservice',
            name='added',
            field=models.IntegerField(null=True),
        ),
    ]
