# Generated by Django 3.2 on 2021-04-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_updatedservice_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmplvarid', models.IntegerField()),
                ('contentid', models.IntegerField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'modx_site_tmplvar_contentvalues',
                'managed': False,
            },
        ),
    ]
