# Generated by Django 3.2 on 2021-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedservice',
            name='status',
            field=models.CharField(default='wait', max_length=20),
        ),
    ]
